In [5]:
import pandas as pd

sg = pd.read_csv("../data/raw/wvs7_singapore.csv", sep=";", index_col=False)

sg.head()

,version,doi,A_YEAR,B_COUNTRY,B_COUNTRY_ALPHA,C_COW_NUM,C_COW_ALPHA,D_INTERVIEW,FW_START,FW_END,...,WEIGHT4A,WEIGHT4B,RESEMAVALBWGT,RESEMAVALWGT,SECVALBWGT,Y001_1,Y001_2,Y001_3,Y001_4,Y001_5
0,6-0-0 (2024-04-15),doi.org/10.14281/18241.20,2020.0,702.0,SGP,830.0,SIN,702070001.0,201911.0,202003.0,...,1.0,1.0,1.0,1.0,0.83,0.0,0.0,0.0,1.0,0.0
1,6-0-0 (2024-04-15),doi.org/10.14281/18241.20,2020.0,702.0,SGP,830.0,SIN,702070002.0,201911.0,202003.0,...,1.0,1.0,1.0,1.0,0.83,1.0,1.0,1.0,0.0,1.0
2,6-0-0 (2024-04-15),doi.org/10.14281/18241.20,2020.0,702.0,SGP,830.0,SIN,702070003.0,201911.0,202003.0,...,1.0,1.0,1.0,1.0,1.00,1.0,0.0,1.0,0.0,1.0
3,6-0-0 (2024-04-15),doi.org/10.14281/18241.20,2020.0,702.0,SGP,830.0,SIN,702070004.0,201911.0,202003.0,...,1.0,1.0,1.0,1.0,1.00,1.0,0.0,0.0,0.0,0.0
4,6-0-0 (2024-04-15),doi.org/10.14281/18241.20,2020.0,702.0,SGP,830.0,SIN,702070005.0,201911.0,202003.0,...,1.0,1.0,1.0,1.0,1.00,0.0,0.0,0.0,0.0,0.0

In [6]:
variables = ["Q275", "Q288", "Q279", "Q273", "Q144", "Q145"]

sg[variables].head()

   Q275  Q288  Q279  Q273  Q144  Q145
0   7.0   5.0   1.0   1.0   2.0   2.0
1   6.0   1.0   1.0   6.0  -2.0   1.0
2   6.0   4.0   1.0   6.0   2.0   2.0
3   6.0   6.0   1.0   1.0   2.0   2.0
4   3.0   8.0   5.0   1.0   2.0   2.0

In [7]:
for var in variables:
    print(f"\n--- {var} ---")
    print(sg[var].value_counts(dropna=False).sort_index())

--- Q275 ---
Q275
-2.0      4
 0.0    117
 1.0    126
 2.0    130
 3.0    341
 4.0    272
 5.0    348
 6.0    502
 7.0    155
 8.0     17
Name: count, dtype: int64

--- Q288 ---
Q288
-2.0      56
 1.0      79
 2.0      77
 3.0     228
 4.0     239
 5.0     588
 6.0     405
 7.0     250
 8.0      74
 9.0       6
 10.0     10
Name: count, dtype: int64

--- Q279 ---
Q279
1.0    971
2.0    186
3.0    135
4.0    271
5.0    216
6.0     89
7.0    128
8.0     16
Name: count, dtype: int64

--- Q273 ---
Q273
1.0    1188
2.0      21
3.0      88
4.0      18
5.0      96
6.0     601
Name: count, dtype: int64

--- Q144 ---
Q144
-2.0       1
 1.0      79
 2.0    1932
Name: count, dtype: int64

--- Q145 ---
Q145
-5.0      10
-2.0       3
-1.0       6
 1.0      66
 2.0    1927
Name: count, dtype: int64

In [8]:
## Q279: Employment status

Q279 is recoded into a binary employment variable.

- 1 = Employed (Q279 = 1, 2, 3)
- 0 = Unemployed (Q279 = 4, 5, 6, 7, 8)

SyntaxError: invalid syntax (1422436917.py, line 3)

In [9]:
employment_map = {
    1: 1,
    2: 1,
    3: 1,
    4: 0,
    5: 0,
    6: 0,
    7: 0,
    8: 0
}

sg["employment"] = sg["Q279"].map(employment_map)

In [10]:
pd.crosstab(sg["Q279"], sg["employment"], dropna=False)

employment    0    1
Q279
1.0           0  971
2.0           0  186
3.0           0  135
4.0         271    0
5.0         216    0
6.0          89    0
7.0         128    0
8.0          16    0