In [8]:
# Malaysia Part B - Data Cleaning
# Sutong

import pandas as pd
import numpy as np

In [9]:
my = pd.read_csv("../data/raw/wvs7_malaysia.csv", sep=";", 
index_col=False) # Prevent pandas from mistakenly treating 1st data column as the index


print(my.shape) #（rows, columns)
my[["Q273", "Q275", "Q279", "Q288", "Q144", "Q145"]].head() #education (Q275); household income (Q288); employment status (Q279); marital status (Q273); personal or family crime victimisation (Q144–Q145)

(1313, 456)

   Q273  Q275  Q279  Q288  Q144  Q145
0   6.0   2.0   6.0   2.0   2.0   1.0
1   6.0   0.0   1.0   3.0   2.0   2.0
2   1.0   2.0   3.0   3.0   2.0   2.0
3   1.0   2.0   3.0   5.0   2.0   2.0
4   1.0   6.0   3.0   4.0   2.0   2.0

In [10]:
vars_b = ["Q275", "Q288", "Q279", "Q273", "Q144", "Q145"]

for var in vars_b:
    print(var)
    print(my[var].value_counts(dropna=False).sort_index())

Q275
Q275
0.0     21
1.0     58
2.0    607
4.0    245
5.0    183
6.0    174
7.0     20
8.0      5
Name: count, dtype: int64
Q288
Q288
1.0      43
2.0      94
3.0     289
4.0     340
5.0     201
6.0      98
7.0     112
8.0      64
9.0      25
10.0     47
Name: count, dtype: int64
Q279
Q279
1.0    786
2.0     38
3.0    149
4.0     73
5.0    128
6.0     85
7.0     46
8.0      8
Name: count, dtype: int64
Q273
Q273
1.0    810
2.0     22
3.0     22
4.0      8
5.0     19
6.0    432
Name: count, dtype: int64
Q144
Q144
1.0     173
2.0    1140
Name: count, dtype: int64
Q145
Q145
1.0     264
2.0    1049
Name: count, dtype: int64

In [11]:
#define missing value
wvs_missing = [-1, -2, -3, -5]

## Clean Education Level
0 = Early childhood / no education
1 = Primary
2 = Lower secondary
3 = Upper secondary
4 = Post-secondary non-tertiary
5 = Short-cycle tertiary
6 = Bachelor
7 = Master
8 = Doctoral

In [12]:
#check distribution of score
my["Q275"].value_counts(dropna=False).sort_index()

Q275
0.0     21
1.0     58
2.0    607
4.0    245
5.0    183
6.0    174
7.0     20
8.0      5
Name: count, dtype: int64

In [13]:
#Although it seems like there is no missing value, just replace missing value for na out of precaution
my["education"] = my["Q275"].replace(wvs_missing, np.nan)

/var/folders/wy/h22gzxs90g30sc89yq2hm2gr0000gn/T/ipykernel_79351/4194467128.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  my["education"] = my["Q275"].replace(wvs_missing, np.nan)

In [14]:
#rename education column to edu
my = my.rename(columns={"education": "edu"})

In [15]:
#check
my["edu"].value_counts(dropna=False).sort_index()

my.loc[
    my["edu"].notna() & ~my["edu"].between(0, 8),
]

Empty DataFrame
Columns: [version, doi, A_YEAR, B_COUNTRY, B_COUNTRY_ALPHA, C_COW_NUM, C_COW_ALPHA, D_INTERVIEW, J_INTDATE, FW_START, FW_END, K_TIME_START, Q_MODE, N_REGION_ISO, N_REGION_WVS, G_TOWNSIZE, G_TOWNSIZE2, H_SETTLEMENT, H_URBRURAL, O1_LONGITUDE, O2_LATITUDE, S_INTLANGUAGE, LNGE_ISO, E_RESPINT, F_INTPRIVACY, E1_LITERACY, W_WEIGHT, S018, PWGHT, Q1, Q2, Q3, Q4, Q5, Q6, Q7, Q8, Q9, Q10, Q11, Q12, Q13, Q14, Q15, Q16, Q17, Q18, Q19, Q20, Q21, Q22, Q23, Q24, Q25, Q26, Q27, Q28, Q29, Q30, Q31, Q32, Q33, Q33_3, Q34, Q34_3, Q35, Q35_3, Q36, Q37, Q38, Q39, Q40, Q41, Q42, Q43, Q44, Q45, Q46, Q47, Q48, Q49, Q50, Q51, Q52, Q53, Q54, Q55, Q56, Q57, Q58, Q59, Q60, Q61, Q62, Q63, Q64, Q65, Q66, Q67, Q68, ...]
Index: []

[0 rows x 457 columns]

## Clean Percieved Household Income Rank

In [16]:
# Check the data type of household income rank
my["Q288"].dtype

dtype('float64')

In [17]:
my["household_income"] = my["Q288"].replace(wvs_missing, np.nan)
my["household_income"].value_counts(dropna=False).sort_index()

/var/folders/wy/h22gzxs90g30sc89yq2hm2gr0000gn/T/ipykernel_79351/1541232447.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  my["household_income"] = my["Q288"].replace(wvs_missing, np.nan)

household_income
1.0      43
2.0      94
3.0     289
4.0     340
5.0     201
6.0      98
7.0     112
8.0      64
9.0      25
10.0     47
Name: count, dtype: int64

In [18]:
# Check any abnormal value: non-missing values but outside the valid 1-10 range
# ~ means not
my.loc[
    my["household_income"].notna() & ~my["household_income"].between(1, 10),
    ["Q288", "household_income"] #see original data and
] #loc[row wanted, column wanted]

Empty DataFrame
Columns: [Q288, household_income]
Index: []

## Clean Employment Status (Q279)
- **1** = Full-time employee (30 hours a week or more)
- **2** = Part-time employee (less than 30 hours a week)
- **3** = Self-employed
- **4** = Retired / pensioned
- **5** = Housewife not otherwise employed
- **6** = Student
- **7** = Unemployed
- **8** = Other

In [19]:
#see distribution
my["Q279"].value_counts(dropna=False).sort_index()

#from the output, we can see there is no missing value

Q279
1.0    786
2.0     38
3.0    149
4.0     73
5.0    128
6.0     85
7.0     46
8.0      8
Name: count, dtype: int64

In [20]:
my["em"] = my["Q279"].map(
    {1:1,
    2:1, 
    3:1,
    4:0, 
    5:0, 
    6:0, 
    7:0, 
    8:0}
)

/var/folders/wy/h22gzxs90g30sc89yq2hm2gr0000gn/T/ipykernel_79351/4037492094.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  my["em"] = my["Q279"].map(

In [21]:
#check
my["em"].value_counts(dropna=False).sort_index

<bound method Series.sort_index of em
1    973
0    340
Name: count, dtype: int64>

In [22]:
#check
my[["Q279", "em"]].head(20)

    Q279  em
0    6.0   0
1    1.0   1
2    3.0   1
3    3.0   1
4    3.0   1
5    1.0   1
6    1.0   1
7    5.0   0
8    1.0   1
9    3.0   1
10   1.0   1
11   6.0   0
12   6.0   0
13   4.0   0
14   1.0   1
15   1.0   1
16   1.0   1
17   1.0   1
18   1.0   1
19   1.0   1

## Clean marital status (Q273)
- 1 Married
- 2 Living together as married
- 3 Divorced
- 4 Separated
- 5 Widowed
- 6 Single

In [23]:
# see distribution
my["Q273"].value_counts(dropna=False)

#there is no missing value

Q273
1.0    810
6.0    432
3.0     22
2.0     22
5.0     19
4.0      8
Name: count, dtype: int64

In [24]:
#recode it in a binary variable: 1 = married; 0 = unmarried
my["marriage"] = my["Q273"].map(
    {
        1:1,
        2:1,
        3:0,
        4:0,
        5:0,
        6:0
    }
)

/var/folders/wy/h22gzxs90g30sc89yq2hm2gr0000gn/T/ipykernel_79351/2097700599.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  my["marriage"] = my["Q273"].map(

In [25]:
#check
my["marriage"].value_counts(dropna=False)

marriage
1    832
0    481
Name: count, dtype: int64

In [26]:
#check
my[["Q273", "marriage"]].head(20)

    Q273  marriage
0    6.0         0
1    6.0         0
2    1.0         1
3    1.0         1
4    1.0         1
5    1.0         1
6    6.0         0
7    1.0         1
8    1.0         1
9    1.0         1
10   1.0         1
11   6.0         0
12   6.0         0
13   1.0         1
14   1.0         1
15   1.0         1
16   1.0         1
17   1.0         1
18   6.0         0
19   1.0         1

## Clean personal or family crime victimisation (Q144–Q145)
1 = Yes
2 = No

In [27]:
my["Q144"].value_counts(dropna=False).sort_index()
#output shows that there is no missing value

Q144
1.0     173
2.0    1140
Name: count, dtype: int64

In [28]:
my['victim_self']=my["Q144"]

/var/folders/wy/h22gzxs90g30sc89yq2hm2gr0000gn/T/ipykernel_79351/2267895993.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  my['victim_self']=my["Q144"]

In [29]:
# Recode Q144 into a binary variable: 1 = victimised, 0 = not victimised
my["victim_self"] = my["Q144"].map({
    1: 1,
    2: 0
})

In [30]:
#check
my[["Q144", "victim_self"]].head(20)

    Q144  victim_self
0    2.0            0
1    2.0            0
2    2.0            0
3    2.0            0
4    2.0            0
5    2.0            0
6    2.0            0
7    2.0            0
8    2.0            0
9    2.0            0
10   2.0            0
11   2.0            0
12   2.0            0
13   1.0            1
14   2.0            0
15   2.0            0
16   2.0            0
17   2.0            0
18   2.0            0
19   2.0            0

In [31]:
my["Q145"].value_counts(dropna=False).sort_index()
#output shows that there is no missing value

Q145
1.0     264
2.0    1049
Name: count, dtype: int64

In [32]:
my["victim_family"] = my["Q145"].map(
    {1: 1,
    2: 0}
)

/var/folders/wy/h22gzxs90g30sc89yq2hm2gr0000gn/T/ipykernel_79351/3701531805.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  my["victim_family"] = my["Q145"].map(

In [33]:
my[["Q145", "victim_family"]].head(20)

    Q145  victim_family
0    1.0              1
1    2.0              0
2    2.0              0
3    2.0              0
4    2.0              0
5    2.0              0
6    2.0              0
7    2.0              0
8    2.0              0
9    2.0              0
10   2.0              0
11   2.0              0
12   2.0              0
13   1.0              1
14   2.0              0
15   2.0              0
16   2.0              0
17   2.0              0
18   2.0              0
19   2.0              0

## Create a new data set with only identifier and cleaned variables

In [34]:
# Find columns that may contain a respondent or interview identifier
[col for col in my.columns
 if "ID" in str(col).upper()
 or "INTERVIEW" in str(col).upper()
 or "CASE" in str(col).upper()]

['D_INTERVIEW']

In [35]:
# Check whether the identifier is unique for every respondent
my["D_INTERVIEW"].nunique()

1313

In [36]:
# Check whether any respondent identifier is missing
my["D_INTERVIEW"].isna().sum()

np.int64(0)

In [37]:
# Keep only the respondent identifier and the variables cleaned in my part
my_part_b = my[
    [
        "D_INTERVIEW",
        "edu",
        "household_income",
        "em",
        "marriage",
        "victim_self",
        "victim_family"
    ]
].copy()

In [38]:
# Preview the processed dataset
my_part_b.head(20)

,D_INTERVIEW,edu,household_income,em,marriage,victim_self,victim_family
0,458070001.0,2.0,2.0,0,0,0,1
1,458070002.0,0.0,3.0,1,0,0,0
2,458070003.0,2.0,3.0,1,1,0,0
3,458070004.0,2.0,5.0,1,1,0,0
4,458070005.0,6.0,4.0,1,1,0,0
5,458070006.0,2.0,4.0,1,1,0,0
6,458070007.0,2.0,3.0,1,0,0,0
7,458070008.0,2.0,4.0,0,1,0,0
8,458070009.0,2.0,5.0,1,1,0,0
9,458070010.0,1.0,4.0,1,1,0,0
10,458070011.0,6.0,5.0,1,1,0,0
11,458070012.0,2.0,4.0,0,0,0,0
12,458070013.0,4.0,6.0,0,0,0,0
13,458070014.0,1.0,3.0,0,1,1,1
14,458070015.0,2.0,4.0,1,1,0,0
15,458070016.0,2.0,4.0,1,1,0,0
16,458070017.0,5.0,4.0,1,1,0,0
17,458070018.0,2.0,5.0,1,1,0,0
18,458070019.0,2.0,3.0,1,0,0,0
19,458070020.0,2.0,2.0,1,1,0,0

In [39]:
# Check the number of respondents and variables
my_part_b.shape

(1313, 7)

In [ ]:
# Save cleaned variables for later merging
# my_part_b.to_csv( "../data/processed/malaysia_part_b_sutong.csv", index=False)

IndentationError: unexpected indent (1524001972.py, line 3)

## Merge part a with part b variables

In [41]:
my_part_a = pd.read_csv("../data/processed/malaysia_part_a_jianru.csv")

In [42]:
#check if my_part_a has the same number of overvations as my_part_b
print(my_part_a.shape)

(1313, 5)

In [43]:
# Check duplicate IDs in jianru's dataset
print(my_part_a["D_INTERVIEW"].duplicated().sum())

0

In [45]:
my_cleaned = my_part_b.merge(
    my_part_a,
    on="D_INTERVIEW",
    how="right",
    validate="one_to_one"
)

In [ ]:
# my_cleaned.to_csv( "../data/processed/malaysia_cleaned.csv", index=False)