In [1]:
import pandas as pd
import numpy as np

In [2]:
yihan = pd.read_csv("../data/processed/clean_sg_part_a_yihan.csv")
junhui = pd.read_csv("../data/processed/clean_sg_part_b_junhui.csv")

In [3]:
print("Yihan shape:", yihan.shape)
print("Junhui shape:", junhui.shape)

print("\nYihan columns:")
print(yihan.columns.tolist())

print("\nJunhui columns:")
print(junhui.columns.tolist())

Yihan shape: (2012, 5)
Junhui shape: (2012, 7)

Yihan columns:
['D_INTERVIEW', 'Q131', 'Q138', 'Q260', 'Q262']

Junhui columns:
['D_INTERVIEW', 'Q275', 'Q288', 'Q279', 'Q273', 'Q144', 'Q145']

In [4]:
print("Yihan unique IDs:", yihan["D_INTERVIEW"].nunique())
print("Junhui unique IDs:", junhui["D_INTERVIEW"].nunique())

print("Yihan duplicate IDs:", yihan["D_INTERVIEW"].duplicated().sum())
print("Junhui duplicate IDs:", junhui["D_INTERVIEW"].duplicated().sum())

Yihan unique IDs: 2012
Junhui unique IDs: 2012
Yihan duplicate IDs: 0
Junhui duplicate IDs: 0

In [5]:
sg_final = pd.merge(
    yihan,
    junhui,
    on="D_INTERVIEW",
    how="inner"
)

print("Merged shape:", sg_final.shape)
sg_final.head()

Merged shape: (2012, 11)

   D_INTERVIEW  Q131  Q138  Q260  Q262  Q275  Q288  Q279  Q273  Q144  Q145
0  702070001.0   2.0   4.0   2.0  37.0   7.0   5.0   1.0   1.0   2.0   2.0
1  702070002.0   2.0   4.0   2.0  42.0   6.0   1.0   1.0   6.0  -2.0   1.0
2  702070003.0   2.0   3.0   1.0  28.0   6.0   4.0   1.0   6.0   2.0   2.0
3  702070004.0   2.0   3.0   2.0  30.0   6.0   6.0   1.0   1.0   2.0   2.0
4  702070005.0   1.0   4.0   2.0  32.0   3.0   8.0   5.0   1.0   2.0   2.0

In [6]:
sg_final.columns.tolist()

['D_INTERVIEW',
 'Q131',
 'Q138',
 'Q260',
 'Q262',
 'Q275',
 'Q288',
 'Q279',
 'Q273',
 'Q144',
 'Q145']

In [7]:
sg_final = sg_final.rename(columns={
    "Q131": "subjective_security",
    "Q138": "sexual_harassment",
    "Q260": "gender",
    "Q262": "age",
    "Q275": "education",
    "Q288": "income",
    "Q279": "employment",
    "Q273": "marital_status",
    "Q144": "victimisation_self",
    "Q145": "victimisation_family"
})

sg_final.head()

,D_INTERVIEW,subjective_security,sexual_harassment,gender,age,education,income,employment,marital_status,victimisation_self,victimisation_family
0,702070001.0,2.0,4.0,2.0,37.0,7.0,5.0,1.0,1.0,2.0,2.0
1,702070002.0,2.0,4.0,2.0,42.0,6.0,1.0,1.0,6.0,-2.0,1.0
2,702070003.0,2.0,3.0,1.0,28.0,6.0,4.0,1.0,6.0,2.0,2.0
3,702070004.0,2.0,3.0,2.0,30.0,6.0,6.0,1.0,1.0,2.0,2.0
4,702070005.0,1.0,4.0,2.0,32.0,3.0,8.0,5.0,1.0,2.0,2.0

In [8]:
sg_final.isna().sum()

D_INTERVIEW             0
subjective_security     0
sexual_harassment       0
gender                  0
age                     0
education               0
income                  0
employment              0
marital_status          0
victimisation_self      0
victimisation_family    0
dtype: int64

In [9]:
age_desc = sg_final["age"].agg([
    "count",
    "mean",
    "std",
    "min",
    "max"
])

age_desc

count    2012.000000
mean       47.783300
std        16.234628
min        21.000000
max        91.000000
Name: age, dtype: float64

In [10]:
def freq_table(df, var):
    table = pd.DataFrame({
        "Frequency": df[var].value_counts(dropna=False).sort_index(),
        "Percent": df[var].value_counts(
            normalize=True,
            dropna=False
        ).sort_index() * 100
    })
    
    table["Percent"] = table["Percent"].round(1)
    return table

In [11]:
freq_table(sg_final, "subjective_security")

                     Frequency  Percent
subjective_security
-2.0                         2      0.1
 1.0                       756     37.6
 2.0                      1093     54.3
 3.0                       152      7.6
 4.0                         9      0.4

In [12]:
freq_table(sg_final, "sexual_harassment")

                   Frequency  Percent
sexual_harassment
-2.0                      11      0.5
 1.0                      16      0.8
 2.0                      66      3.3
 3.0                     466     23.2
 4.0                    1453     72.2

In [13]:
freq_table(sg_final, "gender")

        Frequency  Percent
gender
1.0           924     45.9
2.0          1088     54.1

In [14]:
freq_table(sg_final, "education")

           Frequency  Percent
education
-2.0               4      0.2
 0.0             117      5.8
 1.0             126      6.3
 2.0             130      6.5
 3.0             341     16.9
 4.0             272     13.5
 5.0             348     17.3
 6.0             502     25.0
 7.0             155      7.7
 8.0              17      0.8

In [15]:
freq_table(sg_final, "income")

        Frequency  Percent
income
-2.0           56      2.8
 1.0           79      3.9
 2.0           77      3.8
 3.0          228     11.3
 4.0          239     11.9
 5.0          588     29.2
 6.0          405     20.1
 7.0          250     12.4
 8.0           74      3.7
 9.0            6      0.3
 10.0          10      0.5

In [16]:
freq_table(sg_final, "employment")

            Frequency  Percent
employment
1.0               971     48.3
2.0               186      9.2
3.0               135      6.7
4.0               271     13.5
5.0               216     10.7
6.0                89      4.4
7.0               128      6.4
8.0                16      0.8

In [17]:
freq_table(sg_final, "marital_status")

                Frequency  Percent
marital_status
1.0                  1188     59.0
2.0                    21      1.0
3.0                    88      4.4
4.0                    18      0.9
5.0                    96      4.8
6.0                   601     29.9

In [18]:
freq_table(sg_final, "victimisation_self")

                    Frequency  Percent
victimisation_self
-2.0                        1      0.0
 1.0                       79      3.9
 2.0                     1932     96.0

In [19]:
freq_table(sg_final, "victimisation_family")

                      Frequency  Percent
victimisation_family
-5.0                         10      0.5
-2.0                          3      0.1
-1.0                          6      0.3
 1.0                         66      3.3
 2.0                       1927     95.8

In [20]:
corr_vars = [
    "subjective_security",
    "sexual_harassment",
    "age",
    "education",
    "income",
    "victimisation_self",
    "victimisation_family"
]

In [21]:
corr_table = sg_final[corr_vars].corr(method="spearman")

corr_table

,subjective_security,sexual_harassment,age,education,income,victimisation_self,victimisation_family
subjective_security,1.000000,-0.186820,-0.016576,0.028770,-0.127577,-0.071471,-0.121633
sexual_harassment,-0.186820,1.000000,0.115529,-0.076647,0.031381,0.115311,0.136136
age,-0.016576,0.115529,1.000000,-0.454507,-0.157545,0.050866,0.059851
education,0.028770,-0.076647,-0.454507,1.000000,0.350738,-0.000454,-0.051961
income,-0.127577,0.031381,-0.157545,0.350738,1.000000,0.106512,0.042128
victimisation_self,-0.071471,0.115311,0.050866,-0.000454,0.106512,1.000000,0.284717
victimisation_family,-0.121633,0.136136,0.059851,-0.051961,0.042128,0.284717,1.000000

In [22]:
corr_table.round(2)

,subjective_security,sexual_harassment,age,education,income,victimisation_self,victimisation_family
subjective_security,1.00,-0.19,-0.02,0.03,-0.13,-0.07,-0.12
sexual_harassment,-0.19,1.00,0.12,-0.08,0.03,0.12,0.14
age,-0.02,0.12,1.00,-0.45,-0.16,0.05,0.06
education,0.03,-0.08,-0.45,1.00,0.35,-0.00,-0.05
income,-0.13,0.03,-0.16,0.35,1.00,0.11,0.04
victimisation_self,-0.07,0.12,0.05,-0.00,0.11,1.00,0.28
victimisation_family,-0.12,0.14,0.06,-0.05,0.04,0.28,1.00

In [23]:
from scipy.stats import spearmanr

corr_vars = [
    "subjective_security",
    "sexual_harassment",
    "age",
    "education",
    "income",
    "victimisation_self",
    "victimisation_family"
]

for i in range(len(corr_vars)):
    for j in range(i + 1, len(corr_vars)):
        var1 = corr_vars[i]
        var2 = corr_vars[j]

        temp = sg_final[[var1, var2]].dropna()

        rho, p = spearmanr(temp[var1], temp[var2])

        if p < 0.05:
            print(
                f"{var1} × {var2}: "
                f"rho = {rho:.2f}, p = {p:.3f}"
            )

subjective_security × sexual_harassment: rho = -0.19, p = 0.000
subjective_security × income: rho = -0.13, p = 0.000
subjective_security × victimisation_self: rho = -0.07, p = 0.001
subjective_security × victimisation_family: rho = -0.12, p = 0.000
sexual_harassment × age: rho = 0.12, p = 0.000
sexual_harassment × education: rho = -0.08, p = 0.001
sexual_harassment × victimisation_self: rho = 0.12, p = 0.000
sexual_harassment × victimisation_family: rho = 0.14, p = 0.000
age × education: rho = -0.45, p = 0.000
age × income: rho = -0.16, p = 0.000
age × victimisation_self: rho = 0.05, p = 0.023
age × victimisation_family: rho = 0.06, p = 0.007
education × income: rho = 0.35, p = 0.000
education × victimisation_family: rho = -0.05, p = 0.020
income × victimisation_self: rho = 0.11, p = 0.000
victimisation_self × victimisation_family: rho = 0.28, p = 0.000

In [24]:
corr_display = corr_table.rename(
    index={
        "subjective_security": "Security",
        "sexual_harassment": "Harassment",
        "age": "Age",
        "education": "Education",
        "income": "Income",
        "victimisation_self": "Victimisation (Self)",
        "victimisation_family": "Victimisation (Family)"
    },
    columns={
        "subjective_security": "Security",
        "sexual_harassment": "Harassment",
        "age": "Age",
        "education": "Education",
        "income": "Income",
        "victimisation_self": "Victimisation (Self)",
        "victimisation_family": "Victimisation (Family)"
    }
)

corr_display.round(2)

,Security,Harassment,Age,Education,Income,Victimisation (Self),Victimisation (Family)
Security,1.00,-0.19,-0.02,0.03,-0.13,-0.07,-0.12
Harassment,-0.19,1.00,0.12,-0.08,0.03,0.12,0.14
Age,-0.02,0.12,1.00,-0.45,-0.16,0.05,0.06
Education,0.03,-0.08,-0.45,1.00,0.35,-0.00,-0.05
Income,-0.13,0.03,-0.16,0.35,1.00,0.11,0.04
Victimisation (Self),-0.07,0.12,0.05,-0.00,0.11,1.00,0.28
Victimisation (Family),-0.12,0.14,0.06,-0.05,0.04,0.28,1.00